# sourcePath: "sourcepath/personalizado"
# outputPath: "outputpath/personalizado"
sourcePath: "/home/felipe/Documentos/proyectos/Java/javadocmd/src/main/java/io/github/philbone/javadocmd/"
outputPath: "/home/felipe/Documentos/proyectos/Java/javadocmd/src/main/java/"
outFileName: "README.md"
debugMode: false