#!/bin/bash

# Colores para output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}🚀 Instalando JavaDocMd...${NC}"

# Directorio de instalación
INSTALL_DIR="$HOME/.javadocmd"
JAR_FILE="javadocmd-1.0.0.jar"

# Verificar si el JAR existe en el directorio actual
if [ ! -f "$JAR_FILE" ]; then
    echo -e "${RED}❌ Error: No se encuentra $JAR_FILE en el directorio actual${NC}"
    echo "   Asegúrate de ejecutar este script desde la carpeta donde está el JAR"
    exit 1
fi

# Crear directorio de instalación
echo "📁 Creando directorio de instalación: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"

# Mover el JAR
echo "📦 Moviendo $JAR_FILE a $INSTALL_DIR/"
mv "$JAR_FILE" "$INSTALL_DIR/"

# Verificar que el movimiento fue exitoso
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ JAR movido exitosamente${NC}"
else
    echo -e "${RED}❌ Error al mover el JAR${NC}"
    exit 1
fi

# Detectar shell y configurar alias
SHELL_CONFIG=""
if [ -n "$BASH_VERSION" ]; then
    SHELL_CONFIG="$HOME/.bashrc"
elif [ -n "$ZSH_VERSION" ]; then
    SHELL_CONFIG="$HOME/.zshrc"
else
    echo -e "${YELLOW}⚠️  Shell no identificado, usando .bashrc por defecto${NC}"
    SHELL_CONFIG="$HOME/.bashrc"
fi

# Crear alias
echo "🔧 Configurando alias en $SHELL_CONFIG"
ALIAS_CMD="alias javadocmd='java -jar $INSTALL_DIR/$JAR_FILE'"

# Verificar si el alias ya existe
if grep -q "alias javadocmd=" "$SHELL_CONFIG" 2>/dev/null; then
    echo -e "${YELLOW}⚠️  El alias 'javadocmd' ya existe en $SHELL_CONFIG${NC}"
    echo -e "${YELLOW}   Puedes actualizarlo manualmente si es necesario${NC}"
else
    echo "" >> "$SHELL_CONFIG"
    echo "# Alias for JavaDocMd (auto-generated by install script)" >> "$SHELL_CONFIG"
    echo "$ALIAS_CMD" >> "$SHELL_CONFIG"
    echo -e "${GREEN}✅ Alias agregado a $SHELL_CONFIG${NC}"
fi

# Mensaje final
echo ""
echo -e "${GREEN}🎉 Instalación completada!${NC}"
echo ""
echo "📝 Para usar JavaDocMd inmediatamente, ejecuta:"
echo "   source $SHELL_CONFIG"
echo ""
echo "🚀 Luego puedes usar:"
echo "   javadocmd --help"
echo ""
echo "📋 El JAR está instalado en:"
echo "   $INSTALL_DIR/$JAR_FILE"
